name: grader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Generate autograding.json
      run: dotnet run --project ./.github/classroom/GenerateAutograding -- -e ClassroomTemplate -p 5 -o ./.github/classroom/autograding.json
    - name: Autograding
      uses: education/autograding@v1